import 'package:hive/hive.dart';

// This file will be generated by hive_generator
part 'activity.g.dart';

@HiveType(typeId: 0)
class Activity extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime dateTime;

  @HiveField(2)
  final double distance; // in meters

  @HiveField(3)
  final int durationInSeconds;

  @HiveField(4)
  final String pace;

  @HiveField(5)
  final double altitude;

  // Structure: Segments -> Points -> [Lat, Lng]
  @HiveField(6)
  final List<List<List<double>>> route; // hive doesn't support LatLng, so we use a double

  @HiveField(7)
  final List<String> splits;

  Activity({
    required this.id,
    required this.dateTime,
    required this.distance,
    required this.durationInSeconds,
    required this.pace,
    required this.altitude,
    required this.route,
    required this.splits,
  });
}